### PR TITLE
Fix AWK foo to not move fixed size partition starting sectors

### PR DESCRIPTION
**Pull request by Sebastian-Roth**

### CODE REVIEW

**Comment by Sebastian-Roth** [comment]
@mastacontrola Please take your time and have a close look at this before merging it into the working branch. The issue was introduced with [this commit](https://github.com/FOGProject/fogproject/commit/ef75aef1547f17686c65a2d3a7653e111507ac44#diff-def42937359ff06f0443fffc3a53df12). Do you remember why the logic was changed that way? I am not saying my new proposal is all good. I tested with the issue case we have in that [forum post](https://forums.fogproject.org/topic/11041/deployed-image-boot-loop-black-screen-press-ctrl-alt-delete) and it's fine from my point of view. But I am not sure if this could cause another different issue now.

**Comment by Sebastian-Roth** [comment]
Is there a good reason for even having such a crude fixed list like `1:3:5` I am wondering? How I understand fixed is that those partitions should not be moved at all because it can cause an issue. So what's the point of having 2:4 as resizable but not being able to expand those because 5 (and 3) cannot be moved?!

**Comment by mastacontrola** [comment]
The reasoning being is we've seen some people push their recovery partition to the end of the disk.  The main data partition would only be able to expand until the "fixed start" in this scenario.

**Comment by Sebastian-Roth** [comment]
Well I think our current implementation is kind of to minimalistic. We use the term "fixed" for two different things. One is "fixed size" - probably where it originated from. Though I am not sure if we actually need that I am open for a discussion on this. Why do we need partitions to be fixed in size but are still fully working even if they are moved around. Is that because they have filesystems that we cannot resize?

And the second "fixed" that we have mixed into this is "fixed starting position" which is important for boot partitions (being referenced by a static pointer).

I'd love to entangle those two things and have a new `d1.fixed_start_partitions` list added. Though I have to admit that I haven't looked into the code yet. So I cannot say how big this change would be. What do you think @mastacontrola?

**Comment by fractal13** [comment]
The fixed size partition is to support things like linux swap partitions that probably shouldn't scale with the size of the drive, but are reflective of RAM.  What about Microsoft's and Apple's recovery partitions.  Don't those just have a fixed size need due to the software tools that are stored on them?  I wouldn't want to grow them just because I go to a larger disk.

I believe that was the original reasoning in my mind.

**Comment by Sebastian-Roth** [comment]
Thanks heaps for your reply @fractal13. This kind of supports my theory that fixed size was originally meant to be just that fixed in size. We use it as fixed in start position and fixed in size now. But sometimes we don't really stick to the fixed starting point and therefore break things.

I'll try to come up with a proposal to separate those two things and have a very own list for each: `dX.fixed_size_partitions` and `d1.fixed_start_partitions` (the later being fixed in start and most probably in size as well).

**Comment by Sebastian-Roth** [comment]
One major first step to achieve what I am aiming for would be to properly detect those different types of partitions. So as a preparation for this I am trying to collect the information here: https://github.com/FOGProject/fogproject/issues/195

**Comment by mastacontrola** [comment]
@fractal13 You're correct in the thoughts. Recovery/Reserved partitions should be fixed in size, but where things are starting to head in here is that the fixed size partition assumes the start position of the fixed partition is also unmovable. The unmovable start point should only be on the "boot" volume, whatever that may be.

The reason I'm so cautious on this is some users have their windows layouts set so the Main data partition occurs BEFORE the recovery partition. The moving of start position would be required for the recovery partition, while the total size of the recovery part would remain the same as it was when we captured it.  That's the idea, and I think our current AWK script is VERY close to making this happen appropriately. The only issue, as I'm seeing it currently, is consecutive fixed partitions were the adjacent partition start point is shifted although the prior was fixed, the start position should be identical, or so I thought.

**Pull request closed without merging**
