### PR TITLE
Change color of deploy/upload to avoid error

### PR DESCRIPTION
**Pull request by Shiigehiro**
Add different color for upload and download (similar) icons

### CODE REVIEW

**Comment by Sebastian-Roth** [comment]
@Shiigehiro Thanks for your pull request. I see what you are aiming for and I think it's quite a nice idea. But your code change doesn't work for me. Maybe like this:
```
.icon.fa.fa-download {
    color: #7baa0f
}
.icon.fa.fa-upload {
    color: #ff9c07
}
```
Note the indent style as well.

**Comment by Shiigehiro** [comment]
@Sebastian-Roth This work for me, so yes, this work too with this, just more global, i doesn't know if those icons are used for another thing in FOG

**Comment by Shiigehiro** [comment]
@Sebastian-Roth I will remake all the french translation too, because more than a half is false

**Comment by Shiigehiro** [comment]
Can you pull it ? :o

**Comment by mastacontrola** [comment]
Thank you much for the contribution.

**Pull request merged**
