### PR TITLE
Enhanced network detection in installer

### PR DESCRIPTION
**Pull request by bellegarde-c**
Many enterprise networks disallow ping and direct HTTP(s) connections.
Rework checkInternetConnection() to check DNS issues and then HTTP issues.

### CODE REVIEW

**Review by mastacontrola — COMMENTED** [review]
Hello @bellegarde-c

I hope you're doing well, and sorry I haven't gotten back sooner.

There's a few things about this change that I'm a little confused about.

1. The `$dns_command` is configured but then never used.
2. I tried a site I knew didn't exist and it showed host and nslookup with a non-zero return. Maybe it existed at one point and no longer does? I, for now, have just used getent as I believe this is more versatile.

I also changed the output so the testing can be more verbose.

I added the changes into the working-1.6 branch.
I would ask you to review and make changes accordingly and instead of sending to the `master` please place the changes into `dev-branch` (Master is our release branch so we don't touch this branch until release is ready to go live)

Thank you,

**Comment by bellegarde-c** [comment]
Yes, I saw you already changed the code in dev branch just after sending this. Will report any issue and send you merge request next time I update.

regards,

**Comment by Sebastian-Roth** [comment]
@bellegarde-c @mastacontrola The changes were added to the `working-1.6` branch so far but not to `dev-branch` yet. Would be great to get this into `dev-branch` as well and even better when using the **exact same** code changes so merging the branches later on will be easier.

**Comment by Sebastian-Roth** [comment]
Finally pushed commits to both `working-1.6` (df23d1c) and `dev-branch` (5a3e075) to have them both use the same code. Also adjusted things a bit again.

**Pull request closed without merging**
