### PR TITLE
update french translate

### PR DESCRIPTION
**Pull request by bristow**
Following the [message](https://forums.fogproject.org/topic/15450/update-french-translation-for-fog-1-5-9) on the forum, here is my contribution.

There are still problems in the interface, some strings are not translated but are ok in messages.po.

Thanks for the project!

### CODE REVIEW

**Comment by Sebastian-Roth** [comment]
@bristow Thank you so much for your incredible work on the French translation file!!

May I ask you one favor? Could we leave the header as close to what it was before? Revert/leave the lines `Project-Id-Version`, `Language` to what they were before and maybe even remove the newly added `X-Generator` line if you don't mind. Simply commit those changes to your repo again for this pull request to be updated with the new commit automatically.

On the other hand you are more than welcome to change the `Last-Translator` header line and add your name!

**Comment by Sebastian-Roth** [comment]
About the stuff that's not being translated in the web UI: @mastacontrola would you have a chance to look into this? Find details on this in the forum: https://forums.fogproject.org/post/143757

**Comment by bristow** [comment]
> May I ask you one favor? Could we leave the header as close to what it was before? Revert/leave the lines `Project-Id-Version`, `Language` to what they were before and maybe even remove the newly added `X-Generator` line if you don't mind. Simply commit those changes to your repo again for this pull request to be updated with the new commit automatically.
> 
> On the other hand you are more than welcome to change the `Last-Translator` header line and add your name!

No problem to make these changes. I didn't see that it had been changed because I used POEdit and didn't care about the headers. I will do this as soon as possible.

**Comment by bristow** [comment]
@Sebastian-Roth i think it's ok now.

**Comment by Sebastian-Roth** [comment]
@bristow Sorry for the delay. Looks good to me. Merging it now.

**Pull request merged**
