### PR TITLE
Add security checks

### PR DESCRIPTION
**Pull request by skyrider223**
Add security checks to Quick Host Deletion, Update Product Key, Join multicast session and Approve This Host.

### CODE REVIEW

**Comment by skyrider223** [comment]
bootmenu.class.php doesn't verify properly if user is logged or not regarding, thus allowing bad actor to craft arbitrary request to delete computers, change windows key product and approve host.
(eg : http://xxx.xxx.xxx.xxx/fog/service/ipxe/boot.php?mac=XX:XX:XX:XX:XX&delconf=1 )

**Comment by Sebastian-Roth** [comment]
@skyrider223 Thanks for sending in a PR. While I see your point of securing those iPXE menu tasks I am wondering if people used to have this unsecured will complain about the change.

**Comment by Sebastian-Roth** [comment]
@skyrider223 Would you mind posting a link to this PR in the FOG forums as well to hopefully get some further discussion on this going?

**Comment by skyrider223** [comment]
Hello @Sebastian-Roth,

Sorry for my late reply.
Here we go : https://forums.fogproject.org/topic/16606/add-security-checks-488

Cheers,

**Comment by Sebastian-Roth** [comment]
Bumped the topic in the forums.

**Pull request merged**
