### PR TITLE
Fix bug in group wipe function to honour shutdown flag after action

### PR DESCRIPTION
**Pull request by andyb2000**
Fixing bug #232

### CODE REVIEW

**Comment by Sebastian-Roth** [comment]
Thanks for bringing this up. @mastacontrola Seems good to me, please take a look as well.

@andyb2000 May I ask you to bring in new pull requests against our `working` branch?

**Comment by andyb2000** [comment]
Ah apologies, yes will do that against working. Do you want me to resubmit this pull against working instead? @Sebastian-Roth

**Comment by andyb2000** [comment]
Ah, thanks @Sebastian-Roth I've switched my repo over to working so will submit against that for future, I see you've set the base on here over to working already now. Thanks!

**Comment by mastacontrola** [comment]
Looks good to me, thanks for seeing and helping address it.

**Pull request merged**
