### PR TITLE
FixOperStateFileErrorLog

### PR DESCRIPTION
**Pull request by osiktech**
shameless copy of commit [616e3b01322b6802ba61cdc407ca0a164c610de2](https://github.com/FOGProject/fogproject/commit/616e3b01322b6802ba61cdc407ca0a164c610de2) which made it to stable and dev-branch but NOT to working-1.6 branch

### CODE REVIEW

**Comment by osiktech** [comment]
@darksidemilk another PR but this time exclusively for working-1.6 branch.

**Comment by mastacontrola** [comment]
Can you clarify what's wrong? 

In my opinion the only major difference is the file_exists check?

**Comment by mastacontrola** [comment]
Pushed what I think will fix the problem but with more appropriate evaluations, though similar to the original you provided. Much appreciated in submitting this though.

**Comment by darksidemilk** [comment]
Resolved in this separate commit https://github.com/FOGProject/fogproject/commit/4101c44b9f7c9ad629dc27bee043574c51ad4d8c 
Let us know if that does the trick.

**Comment by osiktech** [comment]
Seems to be working fine. :-)

**Pull request closed without merging**
